name: Build Hugo Site

on:
  push:
    branches:
      - main  # 根据你的分支名称调整

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true  # 确保子模块（如主题）被正确加载

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.140.0'  # 指定 Hugo 版本
          extended: true           # 使用扩展版 Hugo

      - name: Build site
        run: hugo --minify

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'  # 仅在主分支推送时部署
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public